---
title: "data_wrangling"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{data_wrangling}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library (musicDemographicsPackage)
library (gdata)
library (dplyr)
library (tidyr)
library (ggplot2)

```

```{r cars}
dt1 = read.xls("../inst/extdata/statistic_id253915_favorite-music-genres-in-the-us-2018-by-age.xlsx", sheet = 2, skip = 2,header = TRUE)
genres_by_age_2019 = rename(dt1, "Genre" = "X","16-19" ="X16.19","20-24"="X20.24","25-34" ="X25.34","35-44" ="X35.44","45-54" ="X45.54","55-64" ="X55.64","65+" ="X65.") %>% select (-X.1)

dt2 = read.xls("../inst/extdata/statistic_id749666_music-listening-frequency-in-the-us-2017-by-age.xlsx", sheet = 2,  skip = 2,header = TRUE)
listening_frequency_by_age_2017 = rename(dt2, "Generation" = "X","4-6 per week" ="X4.6.times.a.week","1-3 per week"="X1.3.times.a.week","Few Times a Month" ="Few.times.a.month","Monthly or Less" ="Monthly.or.less") %>% select (-X.1)

dt3 = read.xls("../inst/extdata/statistic_id864622_music-genres-which-have-the-most-racial-diversity-in-the-us-2018.xlsx", sheet = 2, skip = 2, header = TRUE)
racialy_diverse_music_2018 = dt3 %>% select (-X.1)

saveRDS(genres_by_age_2019, file="../data/genres_age_1_c")
saveRDS(listening_frequency_by_age_2017, file="../data/genres_age_2_c")
saveRDS(racialy_diverse_music_2018, file="../data/listening_frequency_age_c.rds")
```

```{r}

```

